import "./styles.css";
import logoUrl from "./mogul-logo.svg";
import { openShare } from "./share.ts";
import dkLogo from "./distrokid.png";
import wmpIcon from "./wmp-icon.svg";
const dk = (cls = "dk-mark") => `<img class="${cls}" src="${dkLogo}" alt="" aria-hidden="true">`;
const linkIcon = `<svg class="dk-mark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7-7l-1.7 1.7"/><path d="M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7 7l1.7-1.7"/></svg>`;
const CONNECT = "Connect label or distributor";
const shareIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7"/><path d="M12 3v12"/><path d="m7 8 5-5 5 5"/></svg>`;
const SOURCE_NAMES: Record<string, string> = { DISTROKID: "DistroKid", CD_BABY: "CD Baby", TUNECORE: "TuneCore", UNITEDMASTERS: "UnitedMasters", AWAL: "AWAL", AMUSE: "Amuse", BELIEVE: "Believe" };
const sourceName = (t?: string) => (t ? SOURCE_NAMES[t] ?? t.toLowerCase().replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) : "your distributor");
const sourceMark = (t?: string) => (t === "DISTROKID" ? dk("dk-inline") : "");
import { parseDistroKidReport, mergeExcluded, aggregateByStore, type UsageByStore } from "../../supabase/functions/_shared/distrokid.ts";
import { buildRiaaPackage, packageFileName } from "../../supabase/functions/_shared/riaa-package.ts";
import { zipSync, strToU8 } from "fflate";
import {
  computeCertifications, onTheRise, formatUnits as fmt,
  STREAMS_PER_SINGLE_UNIT, STREAMS_PER_ALBUM_UNIT, GOLD, PLATINUM, DIAMOND,
  type CertItem, type Results, type Level,
} from "../../supabase/functions/_shared/riaa.ts";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").replace(/\/$/, "");
const CLIENT_ID = import.meta.env.VITE_MOGUL_CLIENT_ID ?? "";
const EMBED_ORIGIN = import.meta.env.VITE_MOGUL_EMBED_ORIGIN ?? "https://embed.usemogul.com";
const LIVE = Boolean(SUPABASE_URL && CLIENT_ID);
const fn = (name: string) => `${SUPABASE_URL}/functions/v1/${name}`;

const app = document.getElementById("app")!;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
const monthName = (p: string) => {
  const [y, m] = p.split("-").map(Number);
  return y ? new Date(Date.UTC(y, m - 1, 1)).toLocaleString("en-US", { month: "short", year: "numeric", timeZone: "UTC" }) : "";
};
const big = (n: number) => fmt(n);

function visitorId(): string {
  const make = () => (crypto.randomUUID?.() ?? Math.random().toString(36).slice(2) + Date.now().toString(36)).replace(/[^a-zA-Z0-9-]/g, "");
  try {
    let v = localStorage.getItem("mogul_gold_visitor");
    if (!v) { v = make(); localStorage.setItem("mogul_gold_visitor", v); }
    return v;
  } catch { return ((window as any).__vid ??= make()); }
}

function medal(level: Level, mult = 1, size?: number) {
  const label = { gold: "Gold", platinum: "Plat", multi_platinum: `${mult}×`, diamond: "Diam", none: "—" }[level];
  return `<div class="medal ${level}" ${size ? `style="--size:${size}px"` : ""} aria-hidden="true"><span>${label}</span></div>`;
}

// ---------------------------------------------------------------------------
// Sample data (fictional artist, generated by scripts/generate-sample-data.mjs)
// ---------------------------------------------------------------------------
let sampleCache: Results | null = null;
let sampleStore: UsageByStore[] = [];
let sampleFiles: Array<{ name: string; text: string }> = [];
function sampleResults(): Results {
  if (sampleCache) return sampleCache;
  const files = import.meta.glob("../../sample-data/*.tsv", { query: "?raw", import: "default", eager: true }) as Record<string, string>;
  sampleFiles = Object.entries(files).sort().map(([path, text]) => ({ name: path.split("/").pop()!, text }));
  const parsed = Object.entries(files).sort().map(([path, text]) =>
    parseDistroKidReport(text, { fallbackPeriod: path.match(/(\d{4}-\d{2})/)?.[1] }));
  sampleStore = parsed.flatMap((p) => aggregateByStore(p.rows));
  sampleCache = computeCertifications(parsed.flatMap((p) => p.monthly), mergeExcluded(parsed.map((p) => p.excluded)));
  return sampleCache;
}

function saveBlob(blob: Blob, name: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob); a.download = name; a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 4000);
}

async function downloadPackage(r: Results, item: CertItem, ctx: Ctx, btn: HTMLElement) {
  const label = btn.innerHTML;
  btn.textContent = "Building package…";
  try {
    if (ctx.demo) {
      const files = buildRiaaPackage({ item, artist: item.artist, sourceName: "DistroKid", asOf: r.asOf, byStore: sampleStore, statements: sampleFiles });
      const zip = zipSync(Object.fromEntries(Object.entries(files).map(([k, v]) => [k, strToU8(v)])), { level: 6 });
      saveBlob(new Blob([zip], { type: "application/zip" }), packageFileName(item));
    } else {
      const token = location.hash.replace(/^#r-/, "");
      const res = await fetch(`${fn("riaa-package")}?token=${encodeURIComponent(token)}&item=${encodeURIComponent(item.id)}`);
      if (!res.ok) throw new Error(String(res.status));
      saveBlob(await res.blob(), packageFileName(item));
    }
    btn.innerHTML = label;
  } catch {
    btn.textContent = "Couldn't build it. Try again.";
    setTimeout(() => (btn.innerHTML = label), 3000);
  }
}

// ---------------------------------------------------------------------------
// Pieces
// ---------------------------------------------------------------------------
function nav() {
  return `<nav class="nav wrap">
    <a class="brand" href="#" aria-label="Where's My Plaque? home"><img src="${wmpIcon}" alt="" /><span>Where's My Plaque?</span></a>
    <div class="nav-links">
      <a class="hide-sm" href="#rules">How it's counted</a>
      <a href="#demo">Sample report</a>
    </div>
  </nav>`;
}

function footer() {
  return `<footer class="wrap">
    <p>Estimates from your distributor statements using the RIAA's published unit rules. Not affiliated with or endorsed by the RIAA. Certification requires a label application and an audit by Gelfand, Rennert &amp; Feldman.</p>
    <a class="built-by" href="https://usemogul.com" target="_blank" rel="noopener"><span>Built by</span><img src="${logoUrl}" alt="Mogul" /></a>
  </footer>`;
}

function progressRow(i: CertItem, compact = false, shareable = false) {
  const close = i.next.pct >= 0.9 || (i.monthsToNext !== null && i.monthsToNext <= 2);
  const per = i.type === "album" ? STREAMS_PER_ALBUM_UNIT : STREAMS_PER_SINGLE_UNIT;
  const sub = i.type === "album" ? `Album · ${i.trackCount} tracks` : i.current.level === "none" || compact ? "Single" : `Single · ${i.current.label} now`;
  return `<div class="prog">
    <div class="prog-head">
      ${medal(i.next.level, i.next.multiplier, compact ? 44 : undefined)}
      <div class="prog-title"><b>${esc(i.title)}</b><small><span class="num">${big(i.units)} / ${big(i.next.threshold)}</span> units · ${sub}</small></div>
      <div class="prog-left"><b class="num">${big(i.next.remaining)}</b><small>to ${esc(i.next.label)}</small></div>
    </div>
    <div class="bar ${close ? "hot" : ""}"><i style="width:${Math.max(1.5, i.next.pct * 100).toFixed(1)}%"></i></div>
    ${compact ? "" : `<div class="prog-foot"><span class="${close ? "hot" : ""}">${esc(i.headline)}</span><span class="meta">≈ ${big(i.next.remaining * per)} more US streams${shareable ? `<button class="row-share" data-share-item="${esc(i.id)}" aria-label="Share ${esc(i.title)}">${shareIcon}Share</button>` : ""}</span></div>`}
  </div>`;
}

// ---------------------------------------------------------------------------
// Landing
// ---------------------------------------------------------------------------
function renderLanding() {
  const r = sampleResults();
  const preview = onTheRise(r).filter((i) => i.type === "single").slice(0, 3);
  app.innerHTML = `${nav()}
  <main>
    <section class="hero wrap">
      <div>
        <h1>How close are you to <em>Gold?</em></h1>
        <p class="lede">Connect your label or distributor and see every song and album's distance to Gold, Platinum and Diamond, counted the way the RIAA counts it: US streams and downloads only.</p>
        <div class="cta-row">
          <button class="btn btn-primary" data-act="connect">${linkIcon}${CONNECT}</button>
          <a class="btn btn-ghost" href="#demo">See a sample report</a>
        </div>
        <p class="fineprint">Read-only. Mogul pulls your statements; we never touch your releases or payouts.</p>
      </div>
      <div class="hero-card" aria-label="Sample progress">
        ${preview.map((i) => progressRow(i, true)).join("")}
      </div>
    </section>

    <section class="rules wrap" id="rules">
      <h2>How we count</h2>
      <p>Straight from the RIAA's Digital Single and Album audit requirements. We read your royalty statements, keep only what an auditor would, and add it up.</p>
      <div class="rule-grid">
        <div class="rule"><div class="big num">150 <small>streams</small></div><p>= 1 single unit. So do 1 paid download. Gold single = 75M on-demand US streams.</p></div>
        <div class="rule"><div class="big num">1,500 <small>streams</small></div><p>= 1 album unit, as do 10 track downloads or 1 album download. Every track on the album counts, including the singles you put out first.</p></div>
        <div class="rule"><div class="big num">US <small>only</small></div><p>No international streams, and no TikTok, YouTube Content ID, social or radio plays. We show you what we left out.</p></div>
      </div>
      <div class="ladder"><table>
        <thead><tr><th>Level</th><th>Units</th><th>Single · US streams</th><th>Album · US streams</th></tr></thead>
        <tbody>
          ${[["gold", "Gold", GOLD], ["platinum", "Platinum", PLATINUM], ["multi_platinum", "Multi-Platinum", 2 * PLATINUM], ["diamond", "Diamond", DIAMOND]].map(([lvl, name, u]) => `
          <tr><td><div class="tier-cell">${medal(lvl as Level, 2, 34)}${name}${lvl === "multi_platinum" ? ` <span class="num" style="color:var(--fg-3);font-weight:400">every +1M</span>` : ""}</div></td>
          <td class="num">${big(u as number)}</td><td class="num">${big((u as number) * 150)}</td><td class="num">${big((u as number) * 1500)}</td></tr>`).join("")}
        </tbody></table></div>
    </section>
  </main>${footer()}`;
}

// ---------------------------------------------------------------------------
// Results
// ---------------------------------------------------------------------------
type Ctx = { name: string; demo: boolean; warnings?: string[]; target?: string };
const view = { showAll: false };

const demoBanner = (ctx: Ctx) => ctx.demo ? `<div class="demo-banner"><span><b>Sample data.</b> A made-up artist with two years of distributor statements.</span><button class="btn btn-primary btn-sm" data-act="connect">${linkIcon}${CONNECT}</button></div>` : "";

// One page for everyone: verdict first, then progress on the top tracks, then the numbers.
function renderResults(r: Results, ctx: Ctx) {
  const all = [...r.singles, ...r.albums];
  const earned = all.filter((i) => i.current.level !== "none").sort((a, b) => b.units - a.units);
  const rise = onTheRise(r);
  const [top, ...rest] = rise;
  const listed = earned.length ? rise : rest;
  const shown = view.showAll ? listed : listed.slice(0, 5);
  const excl = Object.entries(r.excluded.byReason).sort((a, b) => b[1] - a[1]);
  const exclMax = Math.max(1, ...excl.map(([, v]) => v));
  const best = earned[0];

  const verdict = best
    ? `<h1 class="verdict">You made it.</h1><p class="sub">${earned.length === 1 ? `${esc(best.title)} has` : `${earned.length} releases have`} enough US units to apply for ${earned.length === 1 ? esc(best.current.label) : "certification"}.</p>`
    : top
      ? `<h1 class="verdict">Not yet.</h1><p class="sub">Nothing's at Gold yet. ${esc(top.title)} is closest, at ${top.next.pct < 0.01 ? "under 1" : Math.round(top.next.pct * 100)}%.</p>`
      : `<h1 class="verdict">Nothing to count yet.</h1><p class="sub">We didn't find any US streams in your statements.</p>`;

  app.innerHTML = `${nav()}
  <main class="wrap results">
    ${demoBanner(ctx)}
    <section class="summary">
      <div class="summary-top">
        <div>
          ${verdict}
        </div>
        <div class="summary-actions">
          <button class="btn btn-primary btn-sm" data-act="share">Share</button>
          <button class="btn btn-ghost btn-sm" data-act="copy" id="copy-btn">Copy link</button>
        </div>
      </div>
    </section>

    ${earned.length ? `<section class="section">
      <div class="section-head"><div><h2>Plaques you've earned</h2><p>Enough US units to apply. The RIAA still needs an application and an audit.</p></div></div>
      <div class="cert-grid">${earned.map((i) => `
        <div class="cert ${i.current.level}">
          ${medal(i.current.level, i.current.multiplier)}
          <b>${esc(i.title)}</b>
          <span class="lvl">${esc(i.current.label)}${i.type === "album" ? " · album" : ""}</span>
          <span class="u num">${big(i.units)}<small>units</small></span>
          <div class="cert-dl">
            <button class="dl-btn" data-dl-menu aria-haspopup="menu">↓ Download</button>
            <div class="dl-menu" role="menu" hidden>
              <button role="menuitem" data-pkg="${esc(i.id)}"><b>RIAA application package</b><small>US sales by DSP, ISRCs, statements, request email (.zip)</small></button>
              <button role="menuitem" data-share-cele="${esc(i.id)}"><b>Share image</b><small>"I went ${esc(i.current.label)}!" card</small></button>
            </div>
          </div>
        </div>`).join("")}</div>
    </section>` : top ? `<section class="section">
      <div class="section-head"><div><h2>Your closest shot</h2></div></div>
      <div class="rise close big-shot">${progressRow(top, false, true)}</div>
    </section>` : ""}

    ${listed.length ? `<section class="section">
      <div class="section-head"><div><h2>${earned.length ? "Next plaques" : "Everything else"}</h2><p>Closest first. Pace is your average over the last 3 months.</p></div></div>
      <div class="rise-list">${shown.map((i) => `<div class="rise ${i.next.pct >= 0.9 ? "close" : ""}">${progressRow(i, false, true)}</div>`).join("")}</div>
      ${listed.length > 5 ? `<button class="btn btn-ghost btn-sm more" data-act="more">${view.showAll ? "Show fewer" : `Show all ${listed.length}`}</button>` : ""}
    </section>` : ""}

    <section class="section numbers">
      <div class="section-head"><div><h2>The numbers</h2><p>From ${esc(sourceName(ctx.target))} statements through ${monthName(r.asOf)}.</p></div></div>
      <div class="stats">
        <div class="stat"><b class="num g">${earned.length}</b><small>Plaques earned</small></div>
        <div class="stat"><b class="num">${r.totals.trackedCount}</b><small>Songs + albums tracked</small></div>
        <div class="stat"><b class="num">${big(r.totals.usStreams)}</b><small>US streams counted</small></div>
        <div class="stat"><b class="num">${big(r.totals.excludedQuantity)}</b><small>Plays not counted</small></div>
      </div>
      <div class="split">
        <div class="panel">
          <h3>What we didn't count</h3>
          <p>These plays show up in your statements but don't count toward RIAA certification.</p>
          ${excl.length ? excl.map(([k, v]) => `<div class="xrow"><span>${esc(k)}</span><span class="num">${big(v)}</span><div class="bar"><i style="width:${(v / exclMax * 100).toFixed(1)}%"></i></div></div>`).join("") : `<p>Nothing excluded.</p>`}
        </div>
        ${earned.length ? `<div class="panel cta">
          <h3>Ready to apply?</h3>
          <p>The RIAA needs label copy, ISRCs and a US sales summary by DSP before the audit. Mogul already has your statements and can put that package together.</p>
          <div><a class="btn btn-primary btn-sm" href="https://usemogul.com" target="_blank" rel="noopener">Talk to Mogul</a></div>
        </div>` : `<div class="panel">
          <h3>How we count</h3>
          <p>150 on-demand US streams or 1 paid download = 1 single unit. Gold is 500K units, about 75M US streams. Albums count 1,500 streams per unit.</p>
          <div><a class="btn btn-ghost btn-sm" href="#rules">Full rules</a></div>
        </div>`}
      </div>
      ${[...r.notes, ...(ctx.warnings ?? [])].map((n) => `<p class="note">${esc(n)}</p>`).join("")}
    </section>
  </main>${footer()}`;

  const shareUrl = ctx.demo ? "https://wheresmyplaque.com" : location.href;
  app.querySelector<HTMLButtonElement>('[data-act="share"]')?.addEventListener("click", () => openShare(r, shareUrl));
  app.querySelectorAll<HTMLButtonElement>("[data-dl-menu]").forEach((b) => b.addEventListener("click", (e) => {
    e.stopPropagation();
    const menu = b.nextElementSibling as HTMLElement;
    const open = menu.hidden;
    app.querySelectorAll<HTMLElement>(".dl-menu").forEach((m) => (m.hidden = true));
    menu.hidden = !open;
  }));
  app.querySelectorAll<HTMLButtonElement>("[data-pkg]").forEach((b) => b.addEventListener("click", () => {
    const item = all.find((i) => i.id === b.dataset.pkg);
    const trigger = b.closest(".cert-dl")!.querySelector<HTMLElement>("[data-dl-menu]")!;
    (b.parentElement as HTMLElement).hidden = true;
    if (item) downloadPackage(r, item, ctx, trigger);
  }));
  app.querySelectorAll<HTMLButtonElement>("[data-share-cele]").forEach((b) => b.addEventListener("click", () => {
    (b.parentElement as HTMLElement).hidden = true;
    openShare(r, shareUrl, { kind: "celebrate", itemId: b.dataset.shareCele });
  }));
  app.querySelectorAll<HTMLButtonElement>("[data-share-item]").forEach((b) =>
    b.addEventListener("click", () => openShare(r, shareUrl, { kind: "countdown", itemId: b.dataset.shareItem })));
  app.querySelector<HTMLButtonElement>('[data-act="more"]')?.addEventListener("click", () => { view.showAll = !view.showAll; renderResults(r, ctx); });
}

function renderLoading(done: number, total: number, msg?: string, opts: { title?: string; eyebrow?: string; actions?: string } = {}) {
  const pct = total ? done / total : 0.05;
  app.innerHTML = `${nav()}<main class="wrap"><section class="loading">
    <div class="eyebrow">${opts.eyebrow ?? "Connected"}</div>
    <h1>${opts.title ?? "Reading your statements"}</h1>
    <p>${msg ?? (total ? `${done} of ${total} statements processed.` : "Waiting for your distributor to finish syncing. This usually takes a few minutes.")}</p>
    ${opts.actions ? `<div class="cta-row">${opts.actions}</div>` : `<div class="bar"><i style="width:${Math.max(4, pct * 100)}%"></i></div>
    <p class="note">You can leave this page. Bookmark it and the results will be here.</p>`}
  </section></main>${footer()}`;
}

// Step-by-step progress shown after connecting. Steps 0-2 track the real sync;
// 3-5 play through quickly once the numbers are in, so people see what's happening.
const STEPS = [
  (src: string) => `Connected to ${src}`,
  () => "Downloading your royalty statements",
  () => "Reading every line of every statement",
  () => "Keeping only US on-demand streams and downloads",
  () => "Applying RIAA unit rules (150 streams = 1 single unit)",
  () => "Ranking your songs by distance to the next plaque",
];
let sawSteps = false;
function renderSteps(active: number, src: string, detail?: string) {
  sawSteps = true;
  app.innerHTML = `${nav()}<main class="wrap"><section class="loading steps">
    <h1>Finding your plaques</h1>
    <ol class="step-list">${STEPS.map((t, i) => `<li class="${i < active ? "done" : i === active ? "active" : ""}"><span class="dot">${i < active ? "✓" : i === active ? '<span class="spinner sm"></span>' : ""}</span><span>${esc(t(src))}${i === active && detail ? `<small>${esc(detail)}</small>` : ""}</span></li>`).join("")}</ol>
    <p class="keep-open"><b>Keep this window open.</b> This usually takes a minute or two.</p>
  </section></main>${footer()}`;
}
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

let pollTimer: number | undefined;
let pollStarted = 0;
async function loadLive(token: string) {
  clearTimeout(pollTimer);
  if (!pollStarted) pollStarted = Date.now();
  const again = (ms: number) => (pollTimer = window.setTimeout(() => loadLive(token), ms));
  const reconnect = `<button class="btn btn-primary" data-act="connect">${linkIcon}Reconnect</button>`;
  try {
    const res = await fetch(`${fn("results")}?token=${encodeURIComponent(token)}`);
    if (res.status === 404) { renderLoading(0, 0, "That results link doesn't match a connection. Connect again to start fresh.", { eyebrow: "Not found", title: "We can't find this report", actions: reconnect }); return; }
    const data = await res.json();
    const src = data.source;
    const name = src?.identity?.name || src?.identity?.accounts?.[0]?.name || "Your catalog";
    if (src.needsReconnect) {
      renderLoading(0, 0, `${esc(sourceName(src.target))} asked for your login again (a password change or a security check). Reconnect and we'll pick up where we left off.`, { eyebrow: "Action needed", title: `Sign in to ${esc(sourceName(src.target))} again`, actions: reconnect });
      return;
    }
    if (src.syncError) {
      renderLoading(0, 0, "Mogul hit an error pulling your statements. We'll keep retrying in the background, or you can reconnect now.", { eyebrow: "Sync problem", title: "Something went wrong on our end", actions: reconnect });
      again(30000); return;
    }
    if (!src.ready) {
      const slow = Date.now() - pollStarted > 10 * 60 * 1000;
      const sName = sourceName(src.target);
      const step = src.reports.total === 0 ? 1 : 2;
      const detail = slow ? "Taking longer than usual. Big catalogs can take up to an hour; you can bookmark this page and come back."
        : step === 1 ? `Waiting on ${sName}` : `${src.reports.ingested} of ${src.reports.total} statements read`;
      renderSteps(step, sName, detail);
      again(slow ? 15000 : 4000); return;
    }
    pollStarted = 0;
    const warnings = [...(src.warnings ?? [])];
    if (src.reports.failed) warnings.push(`${src.reports.failed} of ${src.reports.total} statements couldn't be read, so these numbers may be low. We retry them automatically.`);
    if (src.target && src.target !== "DISTROKID" && data.results.totals.trackedCount === 0) {
      renderLoading(0, 0, `Right now we can read DistroKid statements. Your ${esc(sourceName(src.target))} connection is saved, so your results will show up here as soon as we add it.`, { eyebrow: "Connected", title: `We can't read ${esc(sourceName(src.target))} statements yet`, actions: `<a class="btn btn-ghost" href="#demo">See a sample report</a>` });
      return;
    }
    if (sawSteps) {
      for (let i = 3; i <= STEPS.length; i++) { renderSteps(i, sourceName(src.target)); await wait(650); }
      sawSteps = false;
    }
    renderResults(data.results, { name, demo: false, warnings, target: src.target });
  } catch {
    renderLoading(0, 0, "Lost the connection to our server. Retrying…");
    again(6000);
  }
}

// ---------------------------------------------------------------------------
// Connect modal
// ---------------------------------------------------------------------------
let handle: { destroy: () => void } | null = null;
let connectEl: HTMLElement | null = null;
let tokenCache: { token: string; at: number } | null = null;
const vidOnce = () => visitorId();

async function mintToken(): Promise<string> {
  const r = await fetch(fn("session-token"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ visitorId: vidOnce() }) });
  if (!r.ok) throw new Error("token");
  return (await r.json()).token;
}
// Warm everything the connect flow needs before the click: SDK code + a session token.
function prewarm() {
  if (!LIVE || tokenCache) return;
  import("@usemogul/connect-js").catch(() => {});
  mintToken().then((token) => (tokenCache = { token, at: Date.now() })).catch(() => {});
}

function resumePill(show: boolean) {
  let pill = document.getElementById("resume-pill");
  if (!show) return pill?.remove();
  if (pill) return;
  pill = document.createElement("div");
  pill.id = "resume-pill";
  pill.innerHTML = `<span><i class="live-dot"></i>Connection in progress</span><button class="btn btn-primary btn-sm" data-act="connect">Resume</button><button class="pill-cancel" data-act="cancel-connect">Cancel</button>`;
  document.body.appendChild(pill);
}
function hideConnect() { if (connectEl) { connectEl.hidden = true; resumePill(Boolean(handle)); } }
function destroyConnect() { handle?.destroy(); handle = null; connectEl?.remove(); connectEl = null; resumePill(false); }

async function openConnect() {
  if (connectEl) { connectEl.hidden = false; resumePill(false); return; } // resume the same live session
  const m = document.createElement("div");
  m.className = "modal connect-modal";
  m.innerHTML = `<div class="modal-box" role="dialog" aria-modal="true" aria-label="Connect your label or distributor">
    <div class="modal-head"><span>Connect your label or distributor</span><button data-act="close" aria-label="Minimize">×</button></div>
    ${LIVE ? `<div id="mogul-connect" class="loading-embed"><div class="embed-loader"><span class="spinner"></span>Opening secure connection…</div></div>` : `<div class="modal-body">
      <p>Live connections turn on once this page is pointed at the Supabase backend and a Mogul Connect client ID.</p>
      <p>Until then, the sample report runs the exact same math on two years of made-up DistroKid statements.</p>
      <div><a class="btn btn-primary btn-sm" href="#demo" data-act="close">Open the sample report</a></div></div>`}
  </div>`;
  document.body.appendChild(m);
  connectEl = m;
  // Only the × closes it, and even then the session keeps running behind a Resume pill.
  m.addEventListener("click", (e) => { if ((e.target as HTMLElement).closest('[data-act="close"]')) LIVE ? hideConnect() : destroyConnect(); });
  if (!LIVE) return;

  const vid = vidOnce();
  const { MogulConnect } = await import("@usemogul/connect-js");
  const container = document.getElementById("mogul-connect")!;
  handle = MogulConnect.create({
    origin: EMBED_ORIGIN,
    container,
    clientId: CLIENT_ID,
    getToken: async () => {
      if (tokenCache && Date.now() - tokenCache.at < 4 * 60 * 1000) { const t = tokenCache.token; tokenCache = null; return t; }
      return mintToken();
    },
    onReady: () => container.classList.remove("loading-embed"),
    onSuccess: async ({ sourceId, accountId, connectedIdentity }) => {
      const r = await fetch(fn("source-connected"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ visitorId: vid, sourceId, accountId, connectedIdentity }) });
      const { resultsToken } = await r.json();
      destroyConnect();
      location.hash = `r-${resultsToken}`;
    },
    onExit: () => destroyConnect(),
    onError: (err) => {
      container.classList.remove("loading-embed");
      const box = m.querySelector(".modal-box");
      if (box && !box.querySelector(".connect-err")) box.insertAdjacentHTML("beforeend", `<div class="modal-body connect-err"><p>That didn't connect (${esc(err.code)}). Check your login and try again.</p></div>`);
    },
  });
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------
function route() {
  clearTimeout(pollTimer);
  const h = location.hash.replace(/^#/, "");
  if (h === "demo") renderResults(sampleResults(), { name: "", demo: true, target: "DISTROKID" });
  else if (h.startsWith("r-")) loadLive(h.slice(2));
  else { renderLanding(); if (h === "rules") document.getElementById("rules")?.scrollIntoView(); }
  if (h !== "rules") window.scrollTo(0, 0);
}

document.addEventListener("click", async (e) => {
  if (!(e.target as HTMLElement).closest(".cert-dl")) document.querySelectorAll<HTMLElement>(".dl-menu").forEach((m) => (m.hidden = true));
  const t = (e.target as HTMLElement).closest<HTMLElement>("[data-act]");
  if (!t) return;
  if (t.dataset.act === "connect") openConnect();
  if (t.dataset.act === "cancel-connect") destroyConnect();
  if (t.dataset.act === "copy") {
    try { await navigator.clipboard.writeText(location.href); t.textContent = "Link copied"; }
    catch { t.textContent = location.href; }
    setTimeout(() => (t.textContent = "Copy link"), 2400);
  }
});
document.addEventListener("keydown", (e) => { if (e.key === "Escape") document.querySelector(".share-modal")?.remove(); });
window.addEventListener("hashchange", () => { document.querySelector(".share-modal")?.remove(); route(); });
route();
prewarm();
