import "./styles.css";
import logoUrl from "./mogul-logo.svg";
import { parseDistroKidReport, mergeExcluded } from "../../supabase/functions/_shared/distrokid.ts";
import {
  computeCertifications, onTheRise, formatUnits as fmt,
  STREAMS_PER_SINGLE_UNIT, STREAMS_PER_ALBUM_UNIT, GOLD, PLATINUM, DIAMOND,
  type CertItem, type Results, type Level,
} from "../../supabase/functions/_shared/riaa.ts";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").replace(/\/$/, "");
const CLIENT_ID = import.meta.env.VITE_MOGUL_CLIENT_ID ?? "";
const EMBED_ORIGIN = import.meta.env.VITE_MOGUL_EMBED_ORIGIN ?? "https://embed.usemogul.com";
const LIVE = Boolean(SUPABASE_URL && CLIENT_ID);
const fn = (name: string) => `${SUPABASE_URL}/functions/v1/${name}`;

const app = document.getElementById("app")!;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
const monthName = (p: string) => {
  const [y, m] = p.split("-").map(Number);
  return y ? new Date(Date.UTC(y, m - 1, 1)).toLocaleString("en-US", { month: "short", year: "numeric", timeZone: "UTC" }) : "";
};
const big = (n: number) => fmt(n);

function visitorId(): string {
  const make = () => (crypto.randomUUID?.() ?? Math.random().toString(36).slice(2) + Date.now().toString(36)).replace(/[^a-zA-Z0-9-]/g, "");
  try {
    let v = localStorage.getItem("mogul_gold_visitor");
    if (!v) { v = make(); localStorage.setItem("mogul_gold_visitor", v); }
    return v;
  } catch { return ((window as any).__vid ??= make()); }
}

function medal(level: Level, mult = 1, size?: number) {
  const label = { gold: "Gold", platinum: "Plat", multi_platinum: `${mult}×`, diamond: "Diam", none: "—" }[level];
  return `<div class="medal ${level}" ${size ? `style="--size:${size}px"` : ""} aria-hidden="true"><span>${label}</span></div>`;
}

// ---------------------------------------------------------------------------
// Sample data (fictional artist, generated by scripts/generate-sample-data.mjs)
// ---------------------------------------------------------------------------
let sampleCache: Results | null = null;
function sampleResults(): Results {
  if (sampleCache) return sampleCache;
  const files = import.meta.glob("../../sample-data/*.tsv", { query: "?raw", import: "default", eager: true }) as Record<string, string>;
  const parsed = Object.entries(files).sort().map(([path, text]) =>
    parseDistroKidReport(text, { fallbackPeriod: path.match(/(\d{4}-\d{2})/)?.[1] }));
  sampleCache = computeCertifications(parsed.flatMap((p) => p.monthly), mergeExcluded(parsed.map((p) => p.excluded)));
  return sampleCache;
}

// ---------------------------------------------------------------------------
// Pieces
// ---------------------------------------------------------------------------
function nav() {
  return `<nav class="nav wrap">
    <a class="brand" href="#" aria-label="Gold Tracker home"><img src="${logoUrl}" alt="Mogul" /><span>Gold Tracker</span></a>
    <div class="nav-links">
      <a class="hide-sm" href="#rules">How it's counted</a>
      <a href="#demo">Sample report</a>
    </div>
  </nav>`;
}

function footer() {
  return `<footer class="wrap">
    <p>Estimates from your distributor statements using the RIAA's published unit rules. Not affiliated with or endorsed by the RIAA. Certification requires a label application and an audit by Gelfand, Rennert &amp; Feldman.</p>
    <p>Powered by <a href="https://usemogul.com" target="_blank" rel="noopener">Mogul</a></p>
  </footer>`;
}

function progressRow(i: CertItem, compact = false) {
  const close = i.next.pct >= 0.9 || (i.monthsToNext !== null && i.monthsToNext <= 2);
  const per = i.type === "album" ? STREAMS_PER_ALBUM_UNIT : STREAMS_PER_SINGLE_UNIT;
  const sub = i.type === "album" ? `Album · ${i.trackCount} tracks` : i.current.level === "none" || compact ? "Single" : `Single · ${i.current.label} now`;
  return `<div class="prog">
    <div class="prog-head">
      ${medal(i.next.level, i.next.multiplier, compact ? 44 : undefined)}
      <div class="prog-title"><b>${esc(i.title)}</b><small><span class="num">${big(i.units)} / ${big(i.next.threshold)}</span> units · ${sub}</small></div>
      <div class="prog-left"><b class="num">${big(i.next.remaining)}</b><small>to ${esc(i.next.label)}</small></div>
    </div>
    <div class="bar ${close ? "hot" : ""}"><i style="width:${Math.max(1.5, i.next.pct * 100).toFixed(1)}%"></i></div>
    ${compact ? "" : `<div class="prog-foot"><span class="${close ? "hot" : ""}">${esc(i.headline)}</span><span class="meta">≈ ${big(i.next.remaining * per)} more US streams</span></div>`}
  </div>`;
}

// ---------------------------------------------------------------------------
// Landing
// ---------------------------------------------------------------------------
function renderLanding() {
  const r = sampleResults();
  const preview = onTheRise(r).filter((i) => i.type === "single").slice(0, 3);
  app.innerHTML = `${nav()}
  <main>
    <section class="hero wrap">
      <div>
        <div class="eyebrow">RIAA certification tracker</div>
        <h1>How close are you to <em>Gold?</em></h1>
        <p class="lede">Connect your DistroKid account and see every song and album's distance to Gold, Platinum and Diamond, counted the way the RIAA counts it: US streams and downloads only.</p>
        <div class="cta-row">
          <button class="btn btn-primary" data-act="connect"><span class="dk-mark">dk</span>Connect DistroKid</button>
          <a class="btn btn-ghost" href="#demo">See a sample report</a>
        </div>
        <p class="fineprint">Read-only. Mogul pulls your statements; we never touch your releases or payouts.</p>
      </div>
      <div class="hero-card" aria-label="Sample progress">
        <div class="hc-top"><span><span class="live-dot"></span>Sample artist</span><span class="num">thru ${monthName(r.asOf)}</span></div>
        ${preview.map((i) => progressRow(i, true)).join("")}
      </div>
    </section>

    <section class="rules wrap" id="rules">
      <h2>How we count</h2>
      <p>Straight from the RIAA's Digital Single and Album audit requirements. We read your monthly DistroKid statements, keep only what an auditor would, and add it up.</p>
      <div class="rule-grid">
        <div class="rule"><div class="big num">150 <small>streams</small></div><p>= 1 single unit. So do 1 paid download. Gold single = 75M on-demand US streams.</p></div>
        <div class="rule"><div class="big num">1,500 <small>streams</small></div><p>= 1 album unit, as do 10 track downloads or 1 album download. Every track on the album counts, including the singles you put out first.</p></div>
        <div class="rule"><div class="big num">US <small>only</small></div><p>No international streams, and no TikTok, YouTube Content ID, social or radio plays. We show you what we left out.</p></div>
      </div>
      <div class="ladder"><table>
        <thead><tr><th>Level</th><th>Units</th><th>Single · US streams</th><th>Album · US streams</th></tr></thead>
        <tbody>
          ${[["gold", "Gold", GOLD], ["platinum", "Platinum", PLATINUM], ["multi_platinum", "Multi-Platinum", 2 * PLATINUM], ["diamond", "Diamond", DIAMOND]].map(([lvl, name, u]) => `
          <tr><td><div class="tier-cell">${medal(lvl as Level, 2, 34)}${name}${lvl === "multi_platinum" ? ` <span class="num" style="color:var(--fg-3);font-weight:400">every +1M</span>` : ""}</div></td>
          <td class="num">${big(u as number)}</td><td class="num">${big((u as number) * 150)}</td><td class="num">${big((u as number) * 1500)}</td></tr>`).join("")}
        </tbody></table></div>
    </section>
  </main>${footer()}`;
}

// ---------------------------------------------------------------------------
// Results
// ---------------------------------------------------------------------------
type View = { tab: "single" | "album"; filter: "all" | Level; showAll: boolean };
const view: View = { tab: "single", filter: "all", showAll: false };

function renderResults(r: Results, ctx: { name: string; demo: boolean; warnings?: string[] }) {
  const items = view.tab === "single" ? r.singles : r.albums;
  const certified = items.filter((i) => i.current.level !== "none");
  const riseAll = onTheRise(r).filter((i) => i.type === view.tab);
  const counts: Record<string, number> = {
    all: riseAll.length,
    gold: riseAll.filter((i) => i.next.level === "gold").length,
    platinum: riseAll.filter((i) => i.next.level === "platinum" || i.next.level === "multi_platinum").length,
    diamond: riseAll.filter((i) => i.next.level === "diamond").length,
  };
  const rise = view.filter === "all" ? riseAll : onTheRise(r, view.filter).filter((i) => i.type === view.tab);
  const shown = view.showAll ? rise : rise.slice(0, 6);
  const excl = Object.entries(r.excluded.byReason).sort((a, b) => b[1] - a[1]);
  const exclMax = Math.max(1, ...excl.map(([, v]) => v));
  const closest = riseAll[0];

  app.innerHTML = `${nav()}
  <main class="wrap">
    ${ctx.demo ? `<div class="demo-banner"><span><b>Sample data.</b> A made-up artist with two years of DistroKid statements.</span><button class="btn btn-primary btn-sm" data-act="connect">Connect your DistroKid</button></div>` : ""}
    <section class="summary">
      <div class="summary-top">
        <div>
          <div class="eyebrow">DistroKid · statements through ${monthName(r.asOf)}</div>
          <h1>${esc(ctx.name)}</h1>
          <p class="sub">${r.totals.certifiedCount ? `${r.totals.certifiedCount} release${r.totals.certifiedCount > 1 ? "s have" : " has"} enough units to apply for certification.` : closest ? `Closest to the next plaque: ${esc(closest.title)}, ${Math.round(closest.next.pct * 100)}% of the way to ${closest.next.label}.` : "No US streams found yet."}</p>
        </div>
        <div class="summary-actions">
          <button class="btn btn-ghost btn-sm" data-act="copy" id="copy-btn">Copy link</button>
        </div>
      </div>
      <div class="stats">
        <div class="stat"><b class="num g">${r.totals.certifiedCount}</b><small>Eligible now</small></div>
        <div class="stat"><b class="num">${r.totals.trackedCount}</b><small>Songs + albums tracked</small></div>
        <div class="stat"><b class="num">${big(r.totals.usStreams)}</b><small>US streams counted</small></div>
        <div class="stat"><b class="num">${big(r.totals.excludedQuantity)}</b><small>Plays not counted</small></div>
      </div>
    </section>

    <div class="tabs" role="tablist">
      <button role="tab" data-tab="single" aria-selected="${view.tab === "single"}">Singles <span class="num">${r.singles.length}</span></button>
      <button role="tab" data-tab="album" aria-selected="${view.tab === "album"}">Albums <span class="num">${r.albums.length}</span></button>
    </div>

    <section class="section" style="padding-top:28px">
      <div class="section-head"><div><h2>Eligible now</h2><p>Enough US units to apply. Certification still needs a label application and audit.</p></div></div>
      ${certified.length ? `<div class="cert-grid">${certified.map((i) => `
        <div class="cert ${i.current.level}">
          ${medal(i.current.level, i.current.multiplier)}
          <b>${esc(i.title)}</b>
          <span class="lvl">${esc(i.current.label)}</span>
          <span class="u num">${big(i.units)}<small>units</small></span>
        </div>`).join("")}</div>`
        : `<div class="empty"><b>Nothing at Gold yet.</b> ${view.tab === "album" && !r.albums.length ? "We only treat a release as an album when it has 3 or more tracks." : closest ? `Your closest is ${esc(closest.title)} at ${Math.round(closest.next.pct * 100)}%.` : ""}</div>`}
    </section>

    <section class="section">
      <div class="section-head">
        <div><h2>On the rise</h2><p>Closest to the next level first. Pace is your average over the last 3 months.</p></div>
        <div class="chips" role="group" aria-label="Filter by next level">
          ${(["all", "gold", "platinum", "diamond"] as const).map((f) => `<button class="chip" data-filter="${f}" aria-pressed="${view.filter === f}">${f === "all" ? "All" : `→ ${f[0].toUpperCase() + f.slice(1)}`}<span class="ct">${counts[f]}</span></button>`).join("")}
        </div>
      </div>
      ${shown.length ? `<div class="rise-list">${shown.map((i) => `<div class="rise ${i.next.pct >= 0.9 ? "close" : ""}">${progressRow(i)}</div>`).join("")}</div>` : `<div class="empty">Nothing heading to that level yet.</div>`}
      ${rise.length > 6 ? `<button class="btn btn-ghost btn-sm more" data-act="more">${view.showAll ? "Show fewer" : `Show all ${rise.length}`}</button>` : ""}
    </section>

    <section class="section split">
      <div class="panel">
        <h3>What we didn't count</h3>
        <p>These plays show up in your statements but don't count toward RIAA certification.</p>
        ${excl.length ? excl.map(([k, v]) => `<div class="xrow"><span>${esc(k)}</span><span class="num">${big(v)}</span><div class="bar"><i style="width:${(v / exclMax * 100).toFixed(1)}%"></i></div></div>`).join("") : `<p>Nothing excluded.</p>`}
      </div>
      <div class="panel cta">
        <h3>Ready to apply?</h3>
        <p>The RIAA needs label copy, ISRCs and a US sales summary by DSP before the audit. Mogul already has your statements and can put that package together.</p>
        <div><a class="btn btn-primary btn-sm" href="https://usemogul.com" target="_blank" rel="noopener">Talk to Mogul</a></div>
      </div>
    </section>
    ${[...r.notes, ...(ctx.warnings ?? [])].map((n) => `<p class="note">${esc(n)}</p>`).join("")}
  </main>${footer()}`;

  app.querySelectorAll<HTMLButtonElement>("[data-tab]").forEach((b) => b.onclick = () => { view.tab = b.dataset.tab as View["tab"]; view.filter = "all"; view.showAll = false; renderResults(r, ctx); });
  app.querySelectorAll<HTMLButtonElement>("[data-filter]").forEach((b) => b.onclick = () => { view.filter = b.dataset.filter as View["filter"]; view.showAll = false; renderResults(r, ctx); });
  app.querySelector<HTMLButtonElement>('[data-act="more"]')?.addEventListener("click", () => { view.showAll = !view.showAll; renderResults(r, ctx); });
}

function renderLoading(done: number, total: number, msg?: string) {
  const pct = total ? done / total : 0.05;
  app.innerHTML = `${nav()}<main class="wrap"><section class="loading">
    <div class="eyebrow">Connected</div>
    <h1>Reading your statements</h1>
    <p>${msg ?? (total ? `${done} of ${total} monthly statements processed.` : "Waiting for DistroKid to finish syncing. This usually takes a minute or two.")}</p>
    <div class="bar"><i style="width:${Math.max(4, pct * 100)}%"></i></div>
    <p class="note">You can leave this page. Bookmark it and the results will be here.</p>
  </section></main>${footer()}`;
}

let pollTimer: number | undefined;
async function loadLive(token: string) {
  clearTimeout(pollTimer);
  try {
    const res = await fetch(`${fn("results")}?token=${encodeURIComponent(token)}`);
    if (res.status === 404) { renderLoading(0, 0, "We couldn't find that report. Connect again to start over."); return; }
    const data = await res.json();
    const name = data.source?.identity?.name || data.source?.identity?.accounts?.[0]?.name || "Your catalog";
    if (!data.source.ready) {
      renderLoading(data.source.reports.ingested, data.source.reports.total);
      pollTimer = window.setTimeout(() => loadLive(token), 4000);
      return;
    }
    renderResults(data.results, { name, demo: false, warnings: data.source.warnings });
  } catch {
    renderLoading(0, 0, "Lost the connection to our server. Retrying…");
    pollTimer = window.setTimeout(() => loadLive(token), 6000);
  }
}

// ---------------------------------------------------------------------------
// Connect modal
// ---------------------------------------------------------------------------
let handle: { destroy: () => void } | null = null;
function closeModal() { handle?.destroy(); handle = null; document.querySelector(".modal")?.remove(); }

async function openConnect() {
  closeModal();
  const m = document.createElement("div");
  m.className = "modal";
  m.innerHTML = `<div class="modal-box" role="dialog" aria-modal="true" aria-label="Connect DistroKid">
    <div class="modal-head"><span>Connect DistroKid</span><button data-act="close" aria-label="Close">×</button></div>
    ${LIVE ? `<div id="mogul-connect"></div>` : `<div class="modal-body">
      <p>Live connections turn on once this page is pointed at the Supabase backend and a Mogul Connect client ID.</p>
      <p>Until then, the sample report runs the exact same math on two years of made-up DistroKid statements.</p>
      <div><a class="btn btn-primary btn-sm" href="#demo" data-act="close">Open the sample report</a></div></div>`}
  </div>`;
  document.body.appendChild(m);
  m.addEventListener("click", (e) => { if (e.target === m || (e.target as HTMLElement).closest('[data-act="close"]')) closeModal(); });
  if (!LIVE) return;

  const vid = visitorId();
  const { MogulConnect } = await import("@usemogul/connect-js");
  handle = MogulConnect.create({
    origin: EMBED_ORIGIN,
    container: document.getElementById("mogul-connect")!,
    clientId: CLIENT_ID,
    target: "DISTROKID",
    getToken: async () => {
      const r = await fetch(fn("session-token"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ visitorId: vid }) });
      if (!r.ok) throw new Error("token");
      return (await r.json()).token;
    },
    onSuccess: async ({ sourceId, accountId, connectedIdentity }) => {
      const r = await fetch(fn("source-connected"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ visitorId: vid, sourceId, accountId, connectedIdentity }) });
      const { resultsToken } = await r.json();
      closeModal();
      location.hash = `r-${resultsToken}`;
    },
    onExit: () => closeModal(),
    onError: (err) => {
      const box = document.querySelector(".modal-box");
      if (box) box.insertAdjacentHTML("beforeend", `<div class="modal-body"><p>That didn't connect (${esc(err.code)}). Check your DistroKid login and try again.</p></div>`);
    },
  });
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------
function route() {
  clearTimeout(pollTimer);
  const h = location.hash.replace(/^#/, "");
  if (h === "demo") renderResults(sampleResults(), { name: "June Harbor", demo: true });
  else if (h.startsWith("r-")) loadLive(h.slice(2));
  else { renderLanding(); if (h === "rules") document.getElementById("rules")?.scrollIntoView(); }
  if (h !== "rules") window.scrollTo(0, 0);
}

document.addEventListener("click", async (e) => {
  const t = (e.target as HTMLElement).closest<HTMLElement>("[data-act]");
  if (!t) return;
  if (t.dataset.act === "connect") openConnect();
  if (t.dataset.act === "copy") {
    try { await navigator.clipboard.writeText(location.href); t.textContent = "Link copied"; }
    catch { t.textContent = location.href; }
    setTimeout(() => (t.textContent = "Copy link"), 2400);
  }
});
document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeModal(); });
window.addEventListener("hashchange", route);
route();
